### ISSUE TITLE
how to add tabs with complex filed

### ISSUE THREAD

**Issue by hone5t** [htmlburger/carbon-fields-docs#10]
so is there a way to create complex filed with tabs???

**Comment by m1r0** [comment]
Hey @hone5t,

You can use the `set_layout('tabbed')` method. For more information, checkout the complex field [documentation](https://carbonfields.net/docs/complex-field-setup-methods/).

**Comment by hone5t** [comment]
do you have an example for that with nested complex filed it seems not working for me

**Comment by emohamed** [comment]
Could you please share the code that doesn't seem to work for you and explain how you expect it to work?

**Comment by hone5t** [comment]
Carbon_Container::factory('custom_fields', 'Homepage Options')
	->show_on_post_type('page')
	->add_fields(array(
		Carbon_Field::factory('complex', 'crb_postsm', 'Posts Manager')

			->add_fields('one', 'Two Posts with sizes 2/3 and 1/3', array(
					Carbon_Field::factory('separator', 'sep', 'Two Posts with sizes 2/3 and 1/3'),
					Carbon_Field::factory('html', 'html')
						->set_html('<img src="' . $sdir . '/images/homebox-one.png" style="max-width:100%; height:auto" >'),
					Carbon_Field::factory('date','start_date','activate on')
								->help_text('the date for this post to appear on the home page'),
					Carbon_Field::factory('date','end_date','deactivate on')
								->help_text('the date for this post to dissappear on the home page'),
					Carbon_Field::factory('attachment', 'image_one', 'Box 1 Thumbnail')
						->help_text('Recommended image size: 579 x 272 pixels'),

				) )->set_layout('tabbed')
			->add_fields('two', 'Two Posts with size 1/2', array(
					Carbon_Field::factory('separator', 'sep', 'Two Posts with size 1/2'),
					Carbon_Field::factory('html', 'html')
						->set_html('<img src="' . $sdir . '/images/homebox-two.png" style="max-width:100%; height:auto" >'),
					Carbon_Field::factory('date','start_date','activate on')
								->help_text('the date for this post to appear on the home page'),
					Carbon_Field::factory('date','end_date','deactivate on')
								->help_text('the date for this post to dissappear on the home page'),
					Carbon_Field::factory('attachment', 'image_one', 'Box 1 Thumbnail')
						->help_text('Recommended image size: 488 x 428 pixels'),
					
				) )->set_layout('tabbed')
	));
i would expect two tabs for each one and two

**Comment by hone5t** [comment]
Am i doing something wrong or it not possible
