### ISSUE TITLE
Offtopic: Website down

### ISSUE THREAD

**Issue by Lupul** [htmlburger/carbon-fields-docs#105]
Just a heads-up, the website is not working since a couple of days.

https://downforeveryoneorjustme.com/carbonfields.net
![image](https://user-images.githubusercontent.com/3596864/174496009-dadaf432-3af3-4412-9d2a-7c59a53bf955.png)

**Comment by emohamed** [comment]
Thanks for reporting this issue. The site and docs are loading now.
