### ISSUE TITLE
Complex Filed layout tabbed backwards compatibility 

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields-docs#12]
Many of the themes that I have created use complex fields, and have the layout set to 'tabbed'. With the latest update to Carbon Fields, the layout needs to be 'tabbed-horizontal' now, but everything that I wrote to use 'tabbed' no longer shows it as tabs but is reset back to default.

**Comment by m1r0** [comment]
Hi again @Santana1053,

The "tabbed" layout is deprecated but still backward compatible, it should fallback to "tabbed-horizontal". If this is not the case, please provide some code so we can test it out.

**Comment by Santana1053** [comment]
Upon initial testing it was not working, but after checking again now it seems to be functioning properly now.
