### ISSUE TITLE
Converting legacy keys to new format

### ISSUE THREAD

**Issue by MikkoVirenius** [htmlburger/carbon-fields-docs#19]
How can I convert a legacy key to the new 2.0 compatible format?

I would be nice to have a single function, which takes old key as a parameter and returns a new key.

**Comment by atanas-angelov-dev** [comment]
Hi @MikkoVirenius 

Currently we do not have a migration script for legacy data, however, we have a Legacy Storage Service bundled which dynamically loads old data and converts it to the new format (all in memory - no changes are made to your database) so if your datastores do not find any data in the new format it will fallback to whatever old data can be found.
Once you edit a post/theme option/term etc. the data will be stored in the new format.

The downside of this approach being that some old data may be left over and old data that is not updated will not be usable in some of the new features of 2.0 (e.g. complex meta queries).
