### ISSUE TITLE
Updating complex field is broken in 2.0.0-beta-6.

### ISSUE THREAD

**Issue by MikkoVirenius** [htmlburger/carbon-fields-docs#21]
Updating complex field is broken in 2.0.0-beta-6.

I tried it using example 3 from this document https://github.com/htmlburger/carbon-fields-docs/blob/milestone/2_0/documentation/40-advanced-topics/45-updating-values.md

Fields are rendered correctly in the admin, but no values are saved to the database, so text field is empty in both fields.

**Comment by atanas-angelov-dev** [comment]
Hi @MikkoVirenius 

Thanks for the report - the issue has been fixed in beta 7.
