### ISSUE TITLE
Setting field attributes is broken in 2.0.0-beta.7

### ISSUE THREAD

**Issue by MikkoVirenius** [htmlburger/carbon-fields-docs#22]
I'm trying to set `maxlength` attribute for text field using syntax described in the following document, but it seems to be broken in 2.0.0-beta.7:

https://github.com/htmlburger/carbon-fields-docs/blob/milestone/2_0/documentation/20-fields/210-text.md

I'm only able to add `placeholder` attribute, but not for example `maxlength` or `readonly` attributes.

**Comment by atanas-angelov-dev** [comment]
Thanks for the report - the fix will be available in the next beta release.
