### ISSUE TITLE
set_default_value doesn't work for AssociationField

### ISSUE THREAD

**Issue by sebastiengregoire** [htmlburger/carbon-fields-docs#26]
Hi!
`set_default_value` doesn't work on Association field because of the `strval` used in the body of the function (core/Field.php line 605).

Or maybe I don't have the right input format for this setting.

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @sebastiengregoire !

Note that this is the docs repository so this is not a suitable place for this issue - I've reposted it to the correct repository for you:
https://github.com/htmlburger/carbon-fields/issues/402
