### ISSUE TITLE
Network Container example

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields-docs#32]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Comments

Currently, the page for the new [`network` container](https://carbonfields.net/docs/containers-network/?crb_version=2-2-0) suggests that you reference the `theme_options` docs.

I'm thinking that it may be useful to add some quick examples, particularly since `carbon_get_network_option()` requires a site site ID to be passed.

Further, since the function does not accept `null` for the network site ID (as [`get_network_option()`](https://developer.wordpress.org/reference/functions/get_network_option/) does), it may be helpful to include in the example passing the current `SITE_ID_CURRENT_SITE` (if defined).

**EDIT:** In looking at the code to verify this post, I discovered the `carbon_get_the_network_option()` function, which I was not aware of until now. It may be useful to mention that function on the page as well, since I would imagine (??) that, quite often, you're probably looking to get a network option for the current site ID. YMMV

Semi-related note: `carbon_get_network_option()` should probably allow `null` for the site ID (and thus default to `SITE_ID_CURRENT_SITE`) to be consistent with WordPress's `get_network_option()`.

**EDIT 2:** I am _swamped_ with my current project, but when/if I ever have time, I would be willing to submit a PR for the docs. It may be awhile, though, so if anyone here has time, I would be open to assisting.

**Comment by deqngeorgiev** [comment]
Hi @dmhendricks ,

Thank you for the example. I've slightly modified it and I've merged your pull request  -- https://github.com/htmlburger/carbon-fields-docs/commit/45dff015301ca41446beb2e6b8d3003e222f7feb

**Comment by dmhendricks** [comment]
Thanks @deqngeorgiev (and for fixing my typo!). I will close this for now since there is no other feedback. I/we can re-open or create new issue if other additions/modifications are proposed/desired by users.
