### ISSUE TITLE
Serialized datastore options saved in wp_options (network container)

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields-docs#33]
## Version

  - Carbon Fields: 2.2.0 (plugin)
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Expected Behavior
When using the [Serialized Datastore](https://carbonfields.net/docs/guides-serialized-datastore/) example in a `network` container, values do not save to `wp_sitemeta`.

## Actual Behavior
Instead, they appear to save to `wp_options`.

## Container definition
```php
Container::make( 'network', 'crb_my_network_container', 'CF Test' )
  ->set_page_parent( 'settings.php' )
  ->add_fields( array(
	Field::make( 'set', 'crb_set_field_example', 'My Set Field' )
	  ->set_datastore( new Serialized_Theme_Options_Datastore() )
	  ->add_options( $options )
  )
);
```
## Comments
While this doesn't have an impact on functionality (`carbon_get_network_option()` still works), it seems inconsistent since other `network` container field values are stored in `wp_sitemeta`.

**Comment by deqngeorgiev** [comment]
Hi @dmhendricks ,

The example is for `Theme Options` container so it's expected to save values in `wp_options` table. The `Serialized_Theme_Options_Datastore` class should be modified when using in a `network` container to store values to the `wp_stiemeta`.

**Comment by dmhendricks** [comment]
Thank you, D. Since it is so useful, I feel like it should be a component or in core. However, since it is actually operating as designed, I will close this ticket.
