### ISSUE TITLE
Compatibility PHP 7.2 and Gutenberg blocks

### ISSUE THREAD

**Issue by rinseringma** [htmlburger/carbon-fields-docs#37]
Hi!

First of all; what a great plugin!! So much custom fields and all within code!

But as I'm running PHP7.2 and creating a custom block, the frontend throws an error:
"Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-includes/post-template.php on line 284"

When I deleted that block from the page or change my local server to 7.1, error is gone. I'm guessing something is incompatible with 7.2.

Any change this getting fixed? Thanks in advance!

**Comment by vvasilev-** [comment]
Hi @rinseringma,

Please open your issue at main Carbon Fields [repository](https://github.com/htmlburger/carbon-fields). Also, can you give us more information about your block definition, Carbon Fields version, and WordPress version? Thanks.
