### ISSUE TITLE
update/publish button disabled on wp 4.9.9

### ISSUE THREAD

**Issue by iljamm** [htmlburger/carbon-fields-docs#38]
wp 4.9.9 v3 or carbon fields update/publish button gets disabled. dropped down to carbon fields 2.2, all working fine.

**Comment by vvasilev-** [comment]
Hi @iljamm,

Thank you for your feedback! Please re-open your issue at the [main repository](https://github.com/htmlburger/carbon-fields/issues/new) of Carbon Fields because this one is only for the documentation.
