### ISSUE TITLE
Field type file look and feel issue

### ISSUE THREAD

**Issue by ihsanberahim** [htmlburger/carbon-fields-docs#39]
Before press 'Save Changes' or after press 'Use File' it shows like this

![image](https://user-images.githubusercontent.com/1956846/52550245-37aec380-2e12-11e9-9aba-5a7c31951606.png)

After click 'Save Changes'

![image](https://user-images.githubusercontent.com/1956846/52550217-08985200-2e12-11e9-94de-2c560c406a03.png)

It makes user feel that the upload file not there or not being used. 

How to make the field shows like 'Before' and 'After' press 'Save Changes'?

**Comment by vvasilev-** [comment]
Hi @ihsanberahim,

Thank you for your feedback! Please re-open your issue at the [main repository](https://github.com/htmlburger/carbon-fields/issues/new) of Carbon Fields because this one is only for the documentation.
