### ISSUE TITLE
Gutenberg Blocks Category

### ISSUE THREAD

**Issue by sebastienserre** [htmlburger/carbon-fields-docs#41]
Hello,
I'm developping 2 WP Plugins and use Carbon Fields 3 to create Gutenbergs Block.
if the both plugins are activated then all blocks (with different category name) are grouped in the same Category :-/

**Comment by vvasilev-** [comment]
Hi @sebastienserre,

Thank you for your feedback! Please re-open your issue at the [main repository](https://github.com/htmlburger/carbon-fields/issues/new) of Carbon Fields because this one is only for the documentation.
