### ISSUE TITLE
Gutenberg block name translation

### ISSUE THREAD

**Issue by creatile** [htmlburger/carbon-fields-docs#43]
If you change translation of the block name, the block is no longer available. It should be preferable to use a machine name and a displayed name. This is not really an issue I think but maybe a documentation problem

Block::make( __( 'Block Flexible', 'domain_name' ) )

The code in the editor is the following : 
<!-- wp:carbon-fields/block-flexible {"data":

It should be better to make like fields :
Block::make( 'block_flexible ', __( 'Block Flexible', 'domain_name' ) )

Exemple for fields :
Field::make( 'text', 'cf_gallery_block_title', __( 'Gallery title', 'domain_name' ) )

**Comment by vvasilev-** [comment]
Hi @creatile,

Thank you for your feedback! Please re-open your issue at the [main repository](https://github.com/htmlburger/carbon-fields/issues/new) of Carbon Fields because this one is only for the documentation.
