### ISSUE TITLE
Uncaught Error: Class 'Carbon_Fields\Block'

### ISSUE THREAD

**Issue by Metroslim** [htmlburger/carbon-fields-docs#53]
Hello,
I've just installed Carbon Fields with composer.
I've tried the quickstart example and it works great but when I try the Gutenberg Block example 

```
use Carbon_Fields\Block;

Block::make( __( 'My Shiny Gutenberg Block' ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Block Heading' ) ),
        Field::make( 'image', 'image', __( 'Block Image' ) ),
        Field::make( 'rich_text', 'content', __( 'Block Content' ) ),
    ) )
    ->set_category( 'Perrine Voinson', __( 'Perrine Voinson' ), 'dashicons-admin-multisite' )
    ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
        ?>

        <div class="block">
            <div class="block__heading">
                <h1><?php echo esc_html( $fields['heading'] ); ?></h1>
            </div><!-- /.block__heading -->

            <div class="block__image">
                <?php echo wp_get_attachment_image( $fields['image'], 'full' ); ?>
            </div><!-- /.block__image -->

            <div class="block__content">
                <?php echo apply_filters( 'the_content', $fields['content'] ); ?>
            </div><!-- /.block__content -->
        </div><!-- /.block -->

        <?php
    } );

```
Here is what I got:

Fatal error: Uncaught Error: Class 'Carbon_Fields\Block' not found in E:\DEV\*******\Site\wp-content\themes\*******\includes\carbonfields.php on line 5

Could you help me on this weird php error ?

Many thanks, your work looks awesome btw.

Arnaud

**Comment by jorostoyanov** [comment]
Hi @Metroslim 

Thank you for your kind words.

How do you load the `includes/carbonfields.php`? Do you include it in a function attached to a hook? Can you send me the code that loads the file?

**Comment by Metroslim** [comment]
require get_template_directory().'/includes/carbonfields.php';

**Comment by jorostoyanov** [comment]
You will have to use the `carbon_fields_register_fields` hook to load the file.

Here is an example:

```
add_action( 'carbon_fields_register_fields', 'crb_attach_blocks_definition' );
function crb_attach_blocks_definition() {
    require get_template_directory().'/includes/carbonfields.php';
}
```

You can also see this example here - https://docs.carbonfields.net/#/plugin-quickstart

**Comment by Metroslim** [comment]
Well,

It's working great now, I feel stupid :)

Thanks for your time.

**Comment by jorostoyanov** [comment]
No problem! Glad I was able to help :)

Cheers 🍾
