### ISSUE TITLE
wc_get_products() returns empty array

### ISSUE THREAD

**Issue by vaclavgreif** [htmlburger/carbon-fields-docs#66]
I wanted to create a dropdown with WooCommerce products, using the standard `wc_get_products([])` function returns an empty array though. That's probably because the `carbon_fields_register_fields ` hook is called too early.

Any fix for this?

Thanks!

**Comment by campusboy87** [comment]
Hi! I had a similar problem and was given a solution https://github.com/htmlburger/carbon-fields/issues/323
