### ISSUE TITLE
After plugin activate error 500

### ISSUE THREAD

**Issue by DimkaE** [htmlburger/carbon-fields-docs#76]
Hello!
I've used manual "Plugin Quickstart", installing via composer. And after activate it in admin panel, I get 500 error.
In some reason plugin tryes to open file  _ _ DIR _ _ . '/vendor/autoload.php' (23 line of file /wp-content/plugins/carbon-fields-plugin/carbon-fields-plugin.php).
But directory "vendor" vas created in root dir of site.
So, replacing "_ _ DIR _ _" to "$_SERVER['DOCUMENT_ROOT']" solvig the problem, but it's not good decision.

**Comment by mgomez-tubs** [comment]
make sure you are following the latest version of the docs, the quickstart section in the new version of it has changed to :
```
add_action( 'after_setup_theme', 'crb_load' );
function crb_load() {
    require_once( ABSPATH . '/vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
}
```
